include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    import_of_legacy_library_into_null_safe: ignore
    dead_null_aware_expression: ignore
